### PR TITLE
nixci: cli args 

### PR DESCRIPTION
**Pull request by rsrohitsingh682**
Add support for specifying global options which can be passed on to nix command through nixci.

### CODE REVIEW

**Review by srid — COMMENTED** [review]
I thought of a different idea about how to tackle it.

It is best to modify `nix-rs` crate to take in this access-tokens information: https://github.com/juspay/nix-rs/pull/10

There's one more thing we can refactor in `nixci`. I'll play with this now.

**Comment by srid** [comment]
@rsrohitsingh682 I implemented a much simpler design in https://github.com/srid/nixci/pull/66

Give that a try for the docker image.

**Comment by srid** [comment]
Closing this in favour of the other PR

**Comment by rsrohitsingh682** [comment]
> I thought of a different idea about how to tackle it.
> 
> It is best to modify `nix-rs` crate to take in this access-tokens information: [juspay/nix-rs#10](https://github.com/juspay/nix-rs/pull/10)
> 
> There's one more thing we can refactor in `nixci`. I'll play with this now.

Yup. Even I was thinking we should do it from nix-rs

**Pull request closed without merging**
